name: Coverage

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module-name:
          [store, store-react, store-follow, queue, lock, lauf-runner]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install PNPM
        run: npm install -g pnpm@6
      - run: pnpm install
      - run: cd modules/${{matrix.module-name}} && pnpm run test
      - uses: codecov/codecov-action@v1
        with:
          directory: modules/${{matrix.module-name}}/coverage
          flags: ${{matrix.module-name}}
          # name: ${{matrix.module-name}}
          fail_ci_if_error: true
          verbose: true
