name: Coverage

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module-name: [store, store-react, queue, lock, lauf-runner]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npx pnpm add -g pnpm
      # - run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm
      # - run: npm install -g pnpm
      - run: pnpm install
      - run: cd modules/${{matrix.module-name}} && pnpm run test
      - uses: codecov/codecov-action@v1
        with:
          directory: modules/${{matrix.module-name}}/coverage
          flags: ${{matrix.module-name}}
          # name: ${{matrix.module-name}}
          fail_ci_if_error: true
          verbose: true
