name: Generate and Publish Docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout, build, deploy docs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install PNPM
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run validate
      - run: pnpm run check
      - run: pnpm run docs
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "--recursive --whole-file --delete --verbose"
          SOURCE: "api/"
          TARGET: "/var/www/html/cefn.com/lauf/api/"
